### ISSUE TITLE
Server Name Indication (SNI)

### ISSUE THREAD

**Issue by hrkfdn** [reyk/httpd#17]
A feature that'd be really nice to have is SNI, with which it is possible to listen for more than one virtual SSL host on a single IP.
I suppose this does require an interface in the TLS stack as well, which does not appear to be present in libtls.

More on SNI can be found here: https://en.wikipedia.org/wiki/Server_Name_Indication

**Comment by reyk** [comment]
SNI support is on our list, a libtls API has been discussed with jsing@, but it might take a while and will not be in the 5.7 release.

**Comment by hobarrera** [comment]
Is there any news on SNI support?

**Comment by StupidDutchName** [comment]
Now the Let's Encrypt that does not support wildcard certificates yet, this would be an awesome feature :)

**Comment by 4a6f656c** [comment]
The following diffs add server side SNI support to libtls and enable SNI in httpd:

https://marc.info/?l=openbsd-tech&m=147111154502522&w=2
https://marc.info/?l=openbsd-tech&m=147111164302536&w=2

**Comment by 4a6f656c** [comment]
SNI support now exists in upstream libtls/httpd.

**Comment by reyk** [comment]
done
