### ISSUE TITLE
Support the uWSGI protocol

### ISSUE THREAD

**Issue by afresh1** [reyk/httpd#18]
It would be nice to support the [uWSGI Protocol](http://uwsgi-docs.readthedocs.org/en/latest/Protocol.html) in addition to the FastCGI specification.

[Nginx currently supports it](http://uwsgi-docs.readthedocs.org/en/latest/Nginx.html).

[Many languages support the protocol](http://uwsgi-docs.readthedocs.org/en/latest/LanguagesAndPlatforms.html) and I know it is very common in both Perl and Python.

**Comment by fobser** [comment]
On Tue, Feb 10, 2015 at 08:59:30AM -0800, Andrew Fresh wrote:
> It would be nice to support the [uWSGI Protocol](http://uwsgi-docs.readthedocs.org/en/latest/Protocol.html) in addition to the FastCGI specification.

Uhm, either I'm missing something or that link does not actually
specify the protocol. And google didn't help either.

The "Packet descriptions" table looks really scarry. I don't
understand what it's trying to tell me, but why is it talking about
lua and asp.net?!

> 
> [Nginx currently supports it](http://uwsgi-docs.readthedocs.org/en/latest/Nginx.html).

I'm not going to reverse engineer the nginx code to figure out what
the thing does :)

> 
> [Many languages support the protocol](http://uwsgi-docs.readthedocs.org/en/latest/LanguagesAndPlatforms.html) and I know it is very common in both Perl and Python.

I'm not that familiar with webframeworks, but I'm under the impression
that they usually support multiple protocols (uwsgi / fcgi / ...). Is
that impression correct or is there a considerable amount of web apps
only working with uwsgi?

-- 
I'm not entirely sure you are real.

**Comment by reyk** [comment]
I don't see a reason to add another CGI framework. Unless I get really convincing reasons (except the usual greater/better/faster), I'm going to close this issue very soon.

**Comment by afresh1** [comment]
Better/faster are, I believe, the reasons for this.  If that's not good enough, so be it.

**Comment by jugimaster** [comment]
I believe uWSGI would be specific to Python. If that's implemented, why not other stuff specific to other languages too? And then you've got a mess on your hands. 

On the other hand, a general purpose "proxy_pass" is necessary to support actual web-applications (written in sane languages that are not PHP).

**Comment by fobser** [comment]
On 03/14/15 15:16, jugimaster wrote:
> On the other hand, a general purpose "proxy_pass" is necessary to support actual web-applications (written in sane languages that are not PHP).

the general purpose "proxy_pass" is called relayd(8) :)

**Comment by jugimaster** [comment]
That's fine, but I need to accomplish two things through port 80: serve static files (fast), and respond to requests meant for those actual web-apps.

I'm new to both httpd and relayd, but I doubt I can accomplish both with _one_ of them, and that's a problem (for lots of other people too).

If a web server is going to support web-applications, what sense does it make to _only_ support _PHP_ applications in particular, especially when _all_ the others really need is a general purpose reverse proxy?

**Comment by seanthegeek** [comment]
Came here to say exactly what @jugimaster said. The web is more than PHP.

**Comment by mischapeters** [comment]
Being able to run Python frameworks through httpd would be great!

**Comment by jugimaster** [comment]
Being able to proxy requests to _any_ app server would be even greater :)

**Comment by mischapeters** [comment]
When it's an actual server you could potentially use relayd.

**Comment by jugimaster** [comment]
Sure, but I need to serve static files _and_ web-apps through the same port 80.

**Comment by mischapeters** [comment]
relayd + httpd? ;)

**Comment by leto** [comment]
:+1: to supporting uWSGI, which is extensively used in the Perl and Python communities

**Comment by jugimaster** [comment]
So I'd have relayd proxying requests to httpd? I suppose that would work, but I'm not sure it would be satisfactory.

Anyway, you've got relayd and httpd and they're apparently designed and/or supposed to be used together, but httpd supports FastCGI too. In other words, httpd does for PHP roughly what relayd does for just about any language, and that's kind of weird. Why PHP and nothing else? If one, why not all? 

I'm perfectly fine with httpd not supporting any language specifically, but now it does support PHP for some reason. If relayd is supposed to be the standard solution to passing off requests to web app servers, then it would make sense for the same to apply to PHP apps too.

**Comment by fobser** [comment]
First of all, this is not the complaints department. The easiest way to get  uWSGI supported in httpd is to send a diff.
Failing that, I need to be convinced:
* which frameworks only support uWSGI? I know that perl supports FastCGI, googleing suggests that python can do it, too. Oh, and I heard about this program in OpenBSD base called slowcgi(8). One of these days I need to check out what it does, but I'm under the impression that it can execute scripts written in any language as CGI scripts and wrap that into the FastCGI protocol to serve via httpd.
* a protocol description, preferably in RFC style

**Comment by seanthegeek** [comment]
uWSGI is simply a python native bridge between web gateway protocols like
fastcgi and python frameworks.

See
https://stackoverflow.com/questions/1747266/is-there-a-speed-difference-between-wsgi-and-fcgi

https://www.python.org/dev/peps/pep-0333/

Native uWSGI support in httpd is not absolutely needed, however, it would
be great to be able to relay from another web server (say, a uWSGI server,
or any other), and serve static files from an instance httpd. That way, the
application and its static files can be properly served on the same port in
production.  But this is a separate issue, and I will open one as such.

**Comment by jugimaster** [comment]
@fobser I may be missing something here, but when you talk about "executing scripts" through Fast/slowCGI, it sounds way different from what I and dare I say most people want to do.

For example, I'd have a _Java-based_ web-application server with a long-running web-application waiting for requests on port 8080 or whatever. The Java server by itself is perfectly capable of handling serious load. All I need is a HTTP server in front of that, serving static files fast and proxying other requests to the app server or whatever else they're meant to be handled by. 

Plain TCP or HTTP is enough for proxying, and that way there's no need to worry about how some specific platform does things.

**Comment by fobser** [comment]
On 19/05/15 10:15, jugimaster wrote:
> @fobser <https://github.com/fobser> I may be missing something here, but when you talk about "executing scripts" through Fast/slowCGI, it sounds way different from what I and dare I say most people want to do.

it was a joke

> 
> For example, I'd have a /Java-based/ web-application server with a long-running web-application waiting for requests on port 8080 or whatever. The Java server by itself is perfectly capable of handling serious load. All I need is a HTTP server in front of that, serving static files fast and proxying other requests to the app server or whatever else they're meant to be handled by.
> 
> Plain TCP or HTTP is enough for proxying, and that way there's no need to worry about how some specific platform does things.

We think that that should be handled by relayd and have httpd run on localhost (or some other ip/port) for static files. I'm not entirely sure what the objections are against this (is it a speed thing?). If serving static files and proxying must be done in one daemon for whatever reason I suggest to have a look at nginx which is a perfectly fine http daemon.

**Comment by jugimaster** [comment]
> it was a joke

Well, you were seemingly sternly talking about what it would take to convince you to add support for uWSGI. I doubt many people detected a joke in there.

> We think that that should be handled by relayd and have httpd run on localhost (or some other ip/port) for static files. I'm not entirely sure what the objections are against this (is it a speed thing?).

Alright, I guess that's fine. It's probably at least _perceived_ as a speed thing, but I have no idea if it's actually an issue.

But still, I can't help but feel like it's kind of weird for httpd to support FastCGI, since the purpose it serves is something you intend relayd to be used for with non-FastCGI languages/apps anyway. As far as I know, FastCGI is mostly just used for PHP apps these days, so it looks like you support PHP specifically for some reason, but without supporting other languages while at it. Maybe that's where this confusion stems from.
