### ISSUE TITLE
authentication

### ISSUE THREAD

**Issue by 22decembre** [reyk/httpd#19]
It would be nice to have authentication and controlled access with the most common features :

- bsdauth
- passwd file (classical)
- ldap
- whatever ?

(I believe it's already planned, but I really look forward to see this feature, so I land an issue to follow it.)

Thanks for the great work already done.

**Comment by fobser** [comment]
duplicate of #2

**Comment by reyk** [comment]
Only htpasswd file is and will be supported. I add the label "featuritis" to remind us of extra features (eg. ldap) that we reject now but might want to reinspect later.
