### ISSUE TITLE
gzip

### ISSUE THREAD

**Issue by reyk** [reyk/httpd#21]
> Does the new httpd support gzip compression?
> Planned?

**Comment by reyk** [comment]
No.

You can use gzip in fastcgi backends but static files will not be served with compression. Too many problems are know from other web servers, and people tend to turn it off again.

**Comment by moritzbuhl** [comment]
https://github.com/openbsd/src/commit/8e3d8d5a1b748224c8b53fc9b8845e030ee31e12
