### ISSUE TITLE
reserved identifier violation

### ISSUE THREAD

**Issue by elfring** [reyk/httpd#25]
I would like to point out that identifiers like "[`_HTTP_H`](https://github.com/reyk/httpd/blob/7fdb196d97b9af7ed5e238ce8dca1ed5ad21ebbe/httpd/http.h#L19)" and "[`_HTTPD_H`](https://github.com/reyk/httpd/blob/7fdb196d97b9af7ed5e238ce8dca1ed5ad21ebbe/httpd/httpd.h#L21)" [do not fit](https://www.securecoding.cert.org/confluence/display/c/DCL37-C.+Do+not+declare+or+define+a+reserved+identifier#DCL37-C.Donotdeclareordefineareservedidentifier-NoncompliantCodeExample%28HeaderGuard%29 "Do not use identifiers that are reserved for the compiler implementation.") to the expected naming convention of the C language standard.
Would you like to adjust your selection for unique names?

**Comment by reyk** [comment]
Thanks for pointing this out.

**Comment by fobser** [comment]
I was looking at this when it was reported and we are doing that in other places in the tree, too. Don't know if it's actually a thing and we should sweep the hole tree.

**Comment by reyk** [comment]
I'll at least go through my daemons and fix it later today. I'll send you a diff.

btw. sudo also uses the "noncompliant" headers. And I guess it is still used in some compliant and certified environments? ;-)

I think libraries are different, as they "should" use the reserved space. It is also very common in the BSD kernel - and this is where I adopted the practice. I'm not sure if the source considers historic BSD practice.

**Comment by elfring** [comment]
Do any of your software libraries belong only to the implementation of a compiler for the programming language "C" (or "C++")?

**Comment by reyk** [comment]
I took a while, but I just committed a fix to httpd, relayd, iked, and and snmpd in OpenBSD. git will be synced soon. Thanks for the report.
