### ISSUE TITLE
Remove unnecessary null pointer checks

### ISSUE THREAD

**Issue by elfring** [reyk/httpd#26]
[An extra null pointer check is not needed in functions](http://stackoverflow.com/questions/18775608/free-a-null-pointer-anyway-or-check-first "Do I need to check for NULL before free(p)?") like the following.
* [media_delete](https://github.com/reyk/httpd/blob/7fdb196d97b9af7ed5e238ce8dca1ed5ad21ebbe/httpd/httpd.c#L1193 "media_delete function")
* [server_tls_writecb](https://github.com/reyk/httpd/blob/7fdb196d97b9af7ed5e238ce8dca1ed5ad21ebbe/httpd/server.c#L602 "server_tls_writecb function")

**Comment by reyk** [comment]
I agree with media_delete.

The 2nd case in server_tls_writecb is kept for readability of the buf cleanup.

**Comment by elfring** [comment]
How do you think about to avoid unneeded checks in a consistent way?

**Comment by yegortimoschenko** [comment]
I don't get it. There is nothing wrong with having unneeded checks, and when you build a program it is hard to determine which one is going to be unneeded. What is a consistent way you're talking about?

**Comment by elfring** [comment]
>There is nothing wrong with having unneeded checks,

I disagree to this view.


>and when you build a program it is hard to determine
>which one is going to be unneeded.

I find that the corresponding determination can become easier for some check combinations.


Do you care for effects like the following?
* Reduction of [object code size](https://en.wikipedia.org/wiki/Object_code "Description for object code")
* Less source code for review
* Less conditional jumps which influence [the branch prediction by processors](https://en.wikipedia.org/wiki/Branch_predictor "Description for branch prediction").
* [Inlining opportunities](https://en.wikipedia.org/wiki/Inline_expansion "Description for inline expansion")
* [Cache locality](https://en.wikipedia.org/wiki/Locality_of_reference "Description for locality of reference")

**Comment by elfring** [comment]
How do you think about to improve [the function "media_delete"](https://github.com/reyk/httpd/blob/43aa296392eea581bb39cdc1b3d0a282164c05c6/httpd/httpd.c#L1201 "Update candidate")?
