### ISSUE TITLE
Rewrites

### ISSUE THREAD

**Issue by umpc** [reyk/httpd#27]
Have rewrites been considered? Is it something that devs would consider "featuritis"?

**Comment by mischapeters** [comment]
Rewrites would be a very welcome option.

**Comment by brycv** [comment]
I definitely agree. I'm using a separate instance of nginx just for some rewrites while I would prefer to move everything to httpd.

**Comment by 22decembre** [comment]
@brycv : can you describe your current install ? I am interested, as I want to move out of nginx as well, and think it's good transition.

**Comment by cengizIO** [comment]
@22decembre I'm also curious about any possible installations but I think this is not the right place for that discussion.

**Comment by 22decembre** [comment]
yes indeed, but still interesting. So he can give a link to a good description of the installation.

**Comment by reyk** [comment]
Can you show some examples what kind of rewrites you need? Maybe it can already be done with simple redirections. I don't get the need for complex ones where you could also fix the web app (or use a web proxy).

Otherwise I'll close this issue soon, see https://github.com/reyk/httpd/issues/20

**Comment by mischapeters** [comment]
Without regex doing rewrites would almost be impossible. But one thing that might be useful is if you have a PHP or Python app where you don't want to expose the PHP or Python to the client.
For example something like with NGINX: rewrite ^/(.*)$ /index.php?q=$1 last;

**Comment by brycv** [comment]
The particular redirect I need is this type of redirect from my nginx config (for now) for a link.example.com.

rewrite ^/a/(.*)$ http://www.amazon.com/dp/$1/?tag=example-20 permanent;

This particular one is for Amazon but I also use another one for Newegg and some other sites.

**Comment by slkz9** [comment]
first of all, gratz reyk for all the great work on the httpd. i think it's way past time we needed a secure, non-cluttered web server.

as for the rewrites, i understand the wish to avoid regex abominations, it would however be practical to have some kind of mechanism to hide the sent parameters from the client.

**Comment by noqqe** [comment]
some kind of rewrite (even static ones) would be nice to have. Only thing that is holding me back from migrating everything to httpd

**Comment by reyk** [comment]
Hi,

I just pushed two experimental commits to httpd's github branch:
739f1323fdd1b31986f8d976b287b5a250539ec7
f3f57c7673a69d373ac1b2d64d919ea504d9f7f0

Together they add support for rewrites with pattern matching; using redirects for now.

And sent a diff with an explanation to tech@:
http://marc.info/?l=openbsd-tech&m=143480475721221&w=2

This code is not in OpenBSD yet. I made the unusual move of using the github master branch as a public test bed. This is an exception. As always, get the official code from OpenBSD's CVS.

Reyk

**Comment by mischapeters** [comment]
That looks awesome!

**Comment by mischapeters** [comment]
Does this also allow for rewrites without a redirect?

**Comment by Zer0xf8** [comment]
Wow thanks Reyk! This is the missing piece I'm waiting for to move my production servers to httpd!

**Comment by umpc** [comment]
Thank you Reyk!

**Comment by reyk** [comment]
Rewrites without a redirect aren't supported yet, but the new code will allow to add them later.

**Comment by mischapeters** [comment]
Looking forward to it. Been very happy with both relayd and httpd. Straight forward and does what it's supposed to do. Plain and simple awesome.

**Comment by Zer0xf8** [comment]
@mischapeters good question. Looking forward to advocating for basic rewrites without redirect in the future with this new foundation. That's the missing link to replicate the .htaccess type functionality needed for most MVC frameworks to work on httpd.

**Comment by slkz9** [comment]
This is great. Thank you very much. :]

**Comment by rodolfobandeira** [comment]
+1

**Comment by umpc** [comment]
It appears that what I was asking about originally will be added: https://marc.info/?l=openbsd-tech&m=152761257806283

Closing this.

**Comment by clintmsand** [comment]
Excellent @umpc ! I hadn't seen that tech@ post. Good news.
