### ISSUE TITLE
Issues with example ownCloud config

### ISSUE THREAD

**Issue by mulander** [reyk/httpd#30]
Hi,
I recently wrote a [blog post](http://homing-on-code.blogspot.com/2015/03/puffy-in-cloud.html) about configuring a -CURRENT OpenBSD system with an ownCloud instance. Your [wiki page](https://github.com/reyk/httpd/wiki/Running-ownCloud-with-httpd-on-OpenBSD) was a great resource for it but two issues were uncovered while testing the configuration.

First issue detected by [Bryan Steele](https://twitter.com/canadianbryan) on twitter is an outdated workaround for /forbidden which can now be dropped in favour of the newly introduced 'block' rule.

The second issue is a bit more serious. The original nginx rule for blocking was:

        location ~ ^/(data|config|\.ht|db_structure\.xml|README) {
                deny all;
        }

This rule can be translated as: anything starting with
 - data
 - config
 - .ht
 - db_structure.xml
 - README

should be denied access with a 403.

The corresponding example config for 'data' and 'config' blocks are incorrect:

        location "*/data" {
                root "/forbidden"
        }
        location "*/config" {
                root "/forbidden"
        }

They still allow access by direct name to files in data or config folder for example:

    http://localhost/data/owncloud.db

which results in a file download. This issue is also detected by ownCloud self test on the admin page but only when running on port 80 (plain HTTP).

The issue can be remedied by altering the data and config rules to:

 - "\*/data\*"
 - "\*/config\*"

which correctly blocks downloads from both folders.

**Comment by yegortimoschenko** [comment]
Fixed. [Check it out](https://github.com/reyk/httpd/wiki/Running-ownCloud-with-httpd-on-OpenBSD).

**Comment by mulander** [comment]
Looks good. I think this issue can now be closed.
