### ISSUE TITLE
slowcgi(8) doesn't clean up /run/slowcgi.sock (5.7-current MP#899)

### ISSUE THREAD

**Issue by mischapeters** [reyk/httpd#31]
Not sure if this is the right repo to open this, but in the latest 5.7-current, MP#899, it seems that slowcgi is not cleaning up the sock file after the process is stopped.

```
root@j5:/var/www/run # /etc/rc.d/slowcgi start
slowcgi(ok)
root@j5:/var/www/run # ls -la
total 8
drwxr-xr-x   2 root  daemon  512 Apr  1 14:37 .
drwxr-xr-x  13 root  daemon  512 Mar 31 04:40 ..
srw-rw-rw-   1 root  daemon    0 Apr  1 14:23 bgpd.rsock
srw-rw----   1 www   www       0 Apr  1 14:36 php-fpm.sock
srw-rw----   1 www   www       0 Apr  1 14:37 slowcgi.sock
root@j5:/var/www/run # /etc/rc.d/slowcgi stop
slowcgi(ok)
root@j5:/var/www/run # ls -al
total 8
drwxr-xr-x   2 root  daemon  512 Apr  1 14:37 .
drwxr-xr-x  13 root  daemon  512 Mar 31 04:40 ..
srw-rw-rw-   1 root  daemon    0 Apr  1 14:23 bgpd.rsock
srw-rw----   1 www   www       0 Apr  1 14:36 php-fpm.sock
srw-rw----   1 www   www       0 Apr  1 14:37 slowcgi.sock
```

I found this while trying to figure out why calling /cgi-bin/bgplg wasn't working. I am getting the following error when slowcgi is running.
```
default <ip> - - [01/Apr/2015:14:41:41 +0200] "GET /cgi-bin/bgplg HTTP/1.1" 500 0
server default, client 1 (1 active), <ip>:50829 -> <ip>, empty stdout (500 Internal Server Error)
```

Using the following httpd.conf:
```
server "default" {
        listen on egress port 80
        location "/cgi-bin/*" {
                fastcgi
                root "/"
        }
        location "*.php" {
                fastcgi socket "/run/php-fpm.sock"
        }
        root "/htdocs/www"
        directory { no auto index }
}
```

rc.conf.local
```
bgpd_flags=""
httpd_flags=""
slowcgi_flags=""
pkg_scripts="php_fpm"
```

Let me know if more information or tests are needed.

**Comment by fobser** [comment]
On 04/01/15 13:51, Mischa Peters wrote:
> Not sure if this is the right repo to open this, but in the latest 5.7-current, MP#899, it seems that slowcgi is not cleaning up the sock file after the process is stopped.
> 
> ```
> root@j5:/var/www/run # /etc/rc.d/slowcgi start
> slowcgi(ok)
> root@j5:/var/www/run # ls -la
> total 8
> drwxr-xr-x   2 root  daemon  512 Apr  1 14:37 .
          ^      ^^^^  ^^^^^^
Indeed, notice that it can't; slowcgi drops to www:www.

**Comment by mischapeters** [comment]
This is a default installation of 5.7-current. No modifications have been done on the folders.
php_fpm is cleaning up properly.

```
root@j5:/var/www/run # ls -al
total 8
drwxr-xr-x   2 root  daemon  512 Apr  1 22:35 .
drwxr-xr-x  13 root  daemon  512 Mar 31 04:40 ..
root@j5:/var/www/run # /etc/rc.d/php_fpm start
php_fpm(ok)
root@j5:/var/www/run # ls -al
total 8
drwxr-xr-x   2 root  daemon  512 Apr  1 22:35 .
drwxr-xr-x  13 root  daemon  512 Mar 31 04:40 ..
srw-rw----   1 www   www       0 Apr  1 22:35 php-fpm.sock
root@j5:/var/www/run # /etc/rc.d/slowcgi start
slowcgi(ok)
root@j5:/var/www/run # ls -al
total 8
drwxr-xr-x   2 root  daemon  512 Apr  1 22:35 .
drwxr-xr-x  13 root  daemon  512 Mar 31 04:40 ..
srw-rw----   1 www   www       0 Apr  1 22:35 php-fpm.sock
srw-rw----   1 www   www       0 Apr  1 22:35 slowcgi.sock
root@j5:/var/www/run # /etc/rc.d/php_fpm stop
php_fpm(ok)
root@j5:/var/www/run # ls -al
total 8
drwxr-xr-x   2 root  daemon  512 Apr  1 22:36 .
drwxr-xr-x  13 root  daemon  512 Mar 31 04:40 ..
srw-rw----   1 www   www       0 Apr  1 22:35 slowcgi.sock
root@j5:/var/www/run # /etc/rc.d/slowcgi stop
slowcgi(ok)
root@j5:/var/www/run # ls -al
total 8
drwxr-xr-x   2 root  daemon  512 Apr  1 22:36 .
drwxr-xr-x  13 root  daemon  512 Mar 31 04:40 ..
srw-rw----   1 www   www       0 Apr  1 22:35 slowcgi.sock
```

**Comment by fobser** [comment]
What does that have to do with anything? I think you should brush up on your unix filesystem permissions. /var/www/run is owned by root:daemon, slowcgi creats the socket as root and then drops to www:www. How is the www user supposed to clean up that socket?
More importantly, how is php_fpm able to clean up after it self?
Hint:
` root     24819  0.0  0.0  9760  1272 ??  Ss     9Jan15    6:00.78 php-fpm-5.4: master process (/etc/php-fpm.conf) (php-fpm-5.4)`
Scary, isn't it?

**Comment by mischapeters** [comment]
Why not have the rc.d/slowcgi script take care of it? Wouldn't that solve this minor issue witch should otherwise be done by hand? Or do I need to brush up on something else as well?
