### ISSUE TITLE
Prioritize ciphers

### ISSUE THREAD

**Issue by didrix** [reyk/httpd#33]
In some situations it is more secure or faster to let the server choose the cipher rather than to just pick the first supported cipher from the list provided by the client. I suggest to add an option like nginx's ```ssl_prefer_server_ciphers``` / apache's ```SSLHonorCipherOrder``` or maybe even just make it default behaviour.

This unfortunately requires a change to libtls to allow it to set the ```SSL_OP_CIPHER_SERVER_PREFERENCE``` option:
```SSL_CTX_set_options(ctx->ssl_ctx, SSL_OP_CIPHER_SERVER_PREFERENCE);```

I simply added the line above to lib/libtls/tls_server.c:tls_configure_server() to make it default on my test system.

**Comment by nopjmp** [comment]
You may want to mention this on the openbsd-tech mailing list if you haven't already.

**Comment by leto** [comment]
:+1: to having the server decide cipher priority by default. Not having that setting defined for a TLS server is considered a negative mark in https://www.ssllabs.com/ssltest/

**Comment by reyk** [comment]
This is primarily an option for libressl's libtls and is discussed with Joel Sing in OpenBSD.
