### ISSUE TITLE
Choice of name

### ISSUE THREAD

**Issue by dukedougal** [reyk/httpd#36]
I'm curious about the choice of name for httpd.

From the perspective of searching for documentation about this application, it would have been better if it had a very distinctive name.  I'm already getting confused and lost when searching google because there appear to be a number of web servers with the same or similar names.

If it was named "puffer" or something it would have been much easier to filter out which web server is actually the topic in question.

**Comment by rjc** [comment]
https://github.com/reyk/httpd/wiki/Project-Name

**Comment by dukedougal** [comment]
Oh I see thanks for the info.  A very distinctive name is helpful remove confusion about web documentation for servers with the same or similar names.

**Comment by rjc** [comment]
Given the fact that it is both developed and currently runs only on OpenBSD, search results for "OpenBSD httpd" are unambiguous :^)

**Comment by mischapeters** [comment]
Unfortunately a lot of Apache examples show up still, as this was revered to as httpd as well. Since the daemon is called... httpd.

**Comment by dukedougal** [comment]
It's a pity, the author seems committed to the name for some reason but something distinctive would have been in the interests of people trying to implement. It's a namespace collision.

**Comment by reyk** [comment]
OpenHTTPD would be the most obvious name, but unfortunately it is taken by a project that seems to be dead. It has a OpenBSD-alike web page but is not related to us. I tried to contact the owners but never got a reply. So stick with it: OpenBSD httpd.
