### ISSUE TITLE
httpd + php_fpm configuration

### ISSUE THREAD

**Issue by rodolfobandeira** [reyk/httpd#37]
Hi there,

Would you mind to provide me a quick help to set up php_fpm + httpd working here? So.. 

This is my /etc/httpd.conf:
```
server "example.org" {
        listen on * port 80
        directory { no index, index app.php }
        location "*.php" {
                fastcgi socket "/var/www/run/php-fpm.sock"
                log style combined
        }
        root "/var/www/htdocs/example.org/web"
}
types {
        include "/usr/share/misc/mime.types"
}
```
Checking the configuration:
```
$ sudo httpd -n       
configuration OK
```
Checking php_fpm status:
```
$ sudo /etc/rc.d/php_fpm check  
php_fpm(ok)
```

When I hit `example.org` I'm getting:
`404 Not Found`

When I hit `example.org/app.php` I'm getting:
`500 Internal Server Error`

**Comment by mordak** [comment]
httpd chroots into /var/www by default, so your root and fastcgi socket parameters need to be relative to the chroot. 

Try:
> root "/htdocs/example.org/web"
> fastcgi socket "/run/php-fpm.sock"

**Comment by rodolfobandeira** [comment]
Hi @mordak !

It's working!
Thank you so much!
