### ISSUE TITLE
SCGI

### ISSUE THREAD

**Issue by reyk** [reyk/httpd#40]
From http://fossil-scm.org/xfer/doc/trunk/www/server.wiki:

-----

There are basically four ways to set up a Fossil server:
* A stand-alone server
* Using inetd or xinetd or stunnel
* CGI
* SCGI (a.k.a. SimpleCGI)
Each of these can serve either a single repository, or a directory hierarchy containing many repositories with names ending in ".fossil".

-----

So should httpd support SCGI?

**Comment by reyk** [comment]
No.

It should be possible to use standard CGI with slowcgi.

I wonder why fossil doesn't do FastCGI instead.

**Comment by gavinwahl** [comment]
SCGI is much simpler to implement. I did a working SCGI application in an afternoon from scratch. I started with FastCGI but ended up giving up on it because it was too complicated.
