### ISSUE TITLE
Confusing parse.y variable behaviour inside redirects

### ISSUE THREAD

**Issue by yegortimoschenko** [reyk/httpd#42]
Consider this configuration file:

```
domain="yourdomain.com"
ext_if="egress"

server $domain {
        listen on $ext_if port 80
        block return 301 "https://$domain$REQUEST_URI"
}

server $domain {
        listen on $ext_if tls port 443
}
```

Currently it doesn't substitute `$domain` inside URI, so it ends up redirecting to literally "$domain$REQUEST_URI" instead of redirecting to "yourdomain.com$REQUEST_URI".

I've checked both OpenBSD 5.7 release version of httpd(8) and the current one.

Is it an appropriate behaviour?

**Comment by mischapeters** [comment]
Try:
https://$SERVER_NAME$REQUEST_URI

**Comment by yegortimoschenko** [comment]
Thanks! Makes it much cleaner. I'll close this one for now and, if I'll ever patch `server_expand_http()` function to support external variables, I'll send it to tech.
