### ISSUE TITLE
default-type

### ISSUE THREAD

**Issue by dcat** [reyk/httpd#43]
[server_file.c +352](https://github.com/reyk/httpd/blob/fbefc9a818a5ed612c0df918598057a8b551cb95/httpd/server_file.c#L352)

[server_file.c +350](https://github.com/reyk/httpd/blob/fbefc9a818a5ed612c0df918598057a8b551cb95/httpd/server_file.c#L350)

Can you please add a way to set default Content-Type in httpd.conf?

**Comment by reyk** [comment]
Yes, makes sense.

**Comment by reyk** [comment]
default type text/plain

Added. Just add it globally or per-location.
