### ISSUE TITLE
Support for multiple "index" files

### ISSUE THREAD

**Issue by emx0r** [reyk/httpd#51]
Hello,

would it be possible to extend functionality of "directory index <string>" to allow us to specify multiple index file names? It might be very useful while serving both dynamic & static pages from within one server.

Thank you

**Comment by yegortimoshenko** [comment]
Also see [the corresponding topic at Reddit](https://www.reddit.com/r/openbsd/comments/3c8bok/httpd_multiple_index_files/).

**Comment by reyk** [comment]
Hi, I see the demand but it is currently out of scope. I tag it as featuritis to say "no" but to remind us later.

**Comment by stokito** [comment]
Originally multiple index file names needed to serve old sites developed for MicroSoft IIS which for some reason used default.htm file as index.
But from the reddit topic it looks like you have multiple folders: with a static content and index.html and with dynamic content that is generated with index.php. So in fact you don't need different multiple index file names.
You should configure the interpretation of the php files. The `httpd` doesn't have interpreters configuration but for dynamic content it may call PHP via FastCGI.
So you should configure the FastCGI:

     location "/*" {
          fastcgi
          root "/"
     }

So all requests to the root will be processed by FastCGI.
For PHP there is PHP-FPM which a gateway from FastCGI to plain PHP files.
