### ISSUE TITLE
Some troubles with "Running ownCloud with httpd on OpenBSD"

### ISSUE THREAD

**Issue by mitrofanzzz** [reyk/httpd#73]
Hello Reyk!

My name is Nikita, i am from Russia so sorry for my english.
I had use your manual about owncloud and meet next problem:
```
Exception occurred while logging exception: There is no suitable CSPRNG installed on your system
#0 /owncloud/lib/composer/paragonie/random_compat/lib/random_int.php(156): random_bytes(1)
#1 /owncloud/lib/private/Security/SecureRandom.php(80): random_int(0, 35)
#2 /owncloud/lib/private/legacy/util.php(1132): OC\Security\SecureRandom->generate(10, 'abcdefghijklmno...')
#3 /owncloud/lib/base.php(417): OC_Util::getInstanceId()
#4 /owncloud/lib/base.php(581): OC::initSession()
#5 /owncloud/lib/base.php(1013): OC::init()
#6 /owncloud/index.php(54): require_once('/owncloud/lib/b...')
#7 {main}
```
I "google" this error and find something about needed openSSL. I had installed it but it's not helps me.
Could you help me with that?
Thanx in advance!

**Comment by mitrofanzzz** [comment]
Sorry i forgot some details. Openbsd 6.2 fresh install, owncloud from packages, nothing special.
Thanx again.

**Comment by ghost** [comment]
I also came across this same error when installing drupal and what helped in my case was to install php-mcrypt. Do you have that package installed or not?

**Comment by 4a6f656c** [comment]
FTR this really has nothing to do with httpd... the failure is from PHP's [random_bytes()](http://php.net/manual/en/function.random-bytes.php) function and its failure likely implies that no `/dev/urandom` device node is available within the httpd chroot.

**Comment by mr-infty** [comment]
You make `/dev/urandom` available as follows:

    # mkdir /var/www/dev
    # chown www:www /var/www/dev
    # mknod -m 644 /var/www/dev/urandom c 45 2
    # chown www:www /var/www/dev/urandom

Moreover, you need to remove the `nodev` option from the entry of the `/var` partition in `/etc/fstab`.

**Comment by mitrofanzzz** [comment]
Thanx. Next time i will try.
