### ISSUE TITLE
X-Forwarded-For or X-ClientIP in log

### ISSUE THREAD

**Issue by mischapeters** [reyk/httpd#78]
I have been looking for a way for httpd to be able to log the X-Forwarded-For and/or X-ClientIP header in the log file. I am running relayd in front of a couple of httpd servers and it would be great to see the actual client IP address hitting the server.

Any way this can be done?

**Comment by jeekkd** [comment]
Hi,

I am commenting to chime in, this would be a useful feature for me as well. So there is interest for this! An example is having httpd behind haproxy, currently httpd does not log X-Forwarded-For and/or X-ClientIP so it would be valuable to be able to have client logs on the destination servers for various purposes.

Thanks,

**Comment by reyk** [comment]
Done :)

**Comment by mischapeters** [comment]
\o/
